### PR TITLE
Clean validation

### PR DESCRIPTION
**Pull request by jimkeir**
Add some more validation steps around ATC flows.

### CODE REVIEW

**Comment by meikelm** [comment]
Jim - thank for these. We certainly need more warnings to help users navigate the ATC system.
Would you like me to put you on Laminars mailing list for wed developers ? Its usually easier to bounce ideas for each other and stay in touch who's working on what at any given time.

**Comment by jimkeir** [comment]
Hi,

No problem, I've got more incoming. I'm the author of Traffic Global and 
I'm just trying to head off a few of my most common "bug reports" which 
are actually down to conflicting ATC flows. If you do, please use 
jim@jkcc.co.uk instead of this address though, that's my business email. 
Feel free to mail me there to confirm if you wish, and I've added it to 
the CC list here as well.

Cheers,
Jim

------ Original Message ------

**Comment by meikelm** [comment]
After talking to the XP devs affected by each of these validation changes,

1) the runway-to-short warning should not go into WED. In X-Plane the AI decide themselves about the suitability of any runway for their operations and the numbers 
change with each aircraft and each AI engine revision. We also don't want to push users to change runway physical sizes based on perceived needs to AI operation.

2) The logfile reading change is orthogonal to the intentions why the log is read and reported to the scenery gateway. See also WED-1284.

3) The rules preventing extreme ceiling/visibility requirements are good, as that is obviously bogous and as significant consequences (i.e. flow is practically never used at all). I'm going to merge that into WED 2.3 right now.

**Comment by jimkeir** [comment]
Understood. The runway-length warning was intended to warn about the real crazies rather than to enforce a specific, meter-accurate lower limit, and it was a warning rather than an error for that reason. I've attached a list of runways in the current apt.dat which are less than 75% of their officially-required length; there a sub-1000ft runways designated as taking heavies and a 534ft runway claiming to take commercial jets.

[ShortRunways.txt](https://github.com/X-Plane/xptools/files/4567361/ShortRunways.txt)

Enforcing the DEP frequency should at least be documented. Right now it's not clear what should happen here. If it's a smaller commercial airport with ATC but only a tower frequency, the only options are to invent a DEP-specific frequency or list the same frequency for both tower and departure. Which is correct?

**Comment by meikelm** [comment]
What you are showing there are XP internal debugging messages, usefull for those that work the algorithms inside XP. It does not mean than anything is wrong or less than desiredable with the sceneries. As stated above - how AI decide to us a runway or not is up to XP's algorithms. Austin himself is in charge of that and they are a mix of making things look "plausible" and what exactly would happen in the real world. And they do change over time.

**Comment by jimkeir** [comment]
Actually the contents of that file are the output from my own software, not X-Plane, demonstrating that WED is totally cool with having heavies landing on 600 foot grass strips. However, if that's valid data, so be it.

**Pull request closed without merging**
